version: 0.0
os: linux
files:
  - source: ''
    destination: /home/ubuntu/app/qa
hooks:
   BeforeInstall:
     - location: beforeInstall.sh
       timeout: 1080
       runas: root
   AfterInstall:
     - location: AfterInstall.sh
       timeout: 1080
       runas: root
